include:
- carrito_borrarcarrito.py
kind: ArchiveUploadSpec
name: carrito-borrarcarrito-py-jngZ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: borrarcarrito-71858918-bc8b-4b41-aadc-acbedc705f23
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://carrito-borrarcarrito-py-jngZ
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-06-11T10:48:37Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: borrarcarrito
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: borrarcarrito-71858918-bc8b-4b41-aadc-acbedc705f23
      namespace: default
  requestsPerPod: 1
  resources: {}
