include:
- sendemail.py
kind: ArchiveUploadSpec
name: sendemail-py-Wto8

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: sendemail-a0dac5a8-6158-48c2-ac40-fba5e214c25e
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://sendemail-py-Wto8
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-06-11T10:48:39Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: sendemail
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: sendemail-a0dac5a8-6158-48c2-ac40-fba5e214c25e
      namespace: default
  requestsPerPod: 1
  resources: {}
