include:
- carrito_borrarelemento.py
kind: ArchiveUploadSpec
name: carrito-borrarelemento-py-cX3I

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: borrarelemento-1a768815-b03d-4700-ac89-160ac6960f4c
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://carrito-borrarelemento-py-cX3I
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-06-11T10:48:36Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: borrarelemento
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: borrarelemento-1a768815-b03d-4700-ac89-160ac6960f4c
      namespace: default
  requestsPerPod: 1
  resources: {}
