apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: inicio
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: app.inicio
    packageref:
      name: frontend-pkg
      namespace: default
  requestsPerPod: 1
  resources: {}
