include:
- registrar.py
kind: ArchiveUploadSpec
name: registrar-py-RPyG

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: registrar-12dcf45e-25c3-4c30-a3c6-5de101fff398
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://registrar-py-RPyG
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-06-11T10:48:34Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: registrar
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: registrar-12dcf45e-25c3-4c30-a3c6-5de101fff398
      namespace: default
  requestsPerPod: 1
  resources: {}
