include:
- carrito_comprarcarrito.py
kind: ArchiveUploadSpec
name: carrito-comprarcarrito-py-Obne

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: comprarcarrito-bb2b360c-b3a6-461c-b9f4-eb486975d7d0
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://carrito-comprarcarrito-py-Obne
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-06-11T10:48:39Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: comprarcarrito
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: comprarcarrito-bb2b360c-b3a6-461c-b9f4-eb486975d7d0
      namespace: default
  requestsPerPod: 1
  resources: {}
