include:
- carrito_getcarrito.py
kind: ArchiveUploadSpec
name: carrito-getcarrito-py-90BG

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getcarrito-c1e8746c-c019-4e63-a5e9-148e8f3c9658
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://carrito-getcarrito-py-90BG
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-06-11T10:48:35Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: getcarrito
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: getcarrito-c1e8746c-c019-4e63-a5e9-148e8f3c9658
      namespace: default
  requestsPerPod: 1
  resources: {}
