include:
- main.zip
kind: ArchiveUploadSpec
name: main-zip-5Mv7

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: frontend-pkg
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://main-zip-5Mv7
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-06-11T10:48:26Z"
