apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: sendemail
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: sendemail
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /sendemail
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /sendemail
