apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: borrarcarrito
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: borrarcarrito
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /borrarcarrito
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /borrarcarrito
