apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: login
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: login
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /login
    tls: ""
  method: ""
  methods:
  - POST
  - GET
  prefix: ""
  relativeurl: /login
